apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-for-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      name: client-pod
      labels:
        app: client
    spec:
      containers:
      - image: oxygeniswonderful/kuber
        name: client-docker
        ports:
        - containerPort: 7777
